name: NEXT Deploy CI check
on:
  push:
    branches: main
env:
  NEXT_PUBLIC_GOOGLE_CLIENT_ID: '${{secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID}}'
  NEXT_PUBLIC_GOOGLE_REDIRECT_URI: '${{secrets.NEXT_PUBLIC_GOOGLE_REDIRECT_URI}}'
  NEXT_PUBLIC_GOOGLE_SCOPE: '${{secrets.NEXT_PUBLIC_GOOGLE_SCOPE}}'
  NEXT_PUBLIC_GOOGLE_ANALYTICS: '${{secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS}}'
  NEXT_PUBLIC_API_KEY: '${{secrets.NEXT_PUBLIC_API_KEY}}'
  NEXT_PUBLIC_NOTION_KEY: '${{secrets.NEXT_PUBLIC_NOTION_KEY}}'
  NEXT_PUBLIC_NOTION_DATABASE_ID: '${{secrets.NEXT_PUBLIC_NOTION_DATABASE_ID}}'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.
        uses: actions/checkout@main

      - name: Install Dependencies
        run: |
          npm install

      - name: build CI check
        run: |
          npm run build
